import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import Link from 'next/link';

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <header>
        <p>This is a custom homepage built using Next.js and TypeScript.</p>
      <Link href="/">
        <button>Main Page</button>
      </Link>
        </header>
        <main>{children}</main>
      </body>
    </html>
  );
}
