name: CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # Checkout the code using the latest action
    - name: Checkout code
      uses: actions/checkout@v3

    # Set up Node.js
    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '20'

    # Change to the directory where package.json is located
    - name: Change directory to frontend
      working-directory: ./frontend  # Modify this based on your project structure

    # Install dependencies
    - name: Install dependencies
      run: npm install

    # Run tests
    - name: Run tests
      run: npm test

    # Build the project (if applicable)
    - name: Build the project
      run: npm run build

    # Lint the code (optional)
    - name: Lint the code
      run: npm run lint
