name: Vercel Deploy Frontend

env:
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
on:
  pull_request:
    branches: [ "main" ]
    types:
      - closed
jobs:
  Test:
    if: github.event.pull_request.merged == true
    uses: ppw0021/CISE-1b/.github/workflows/test.yml@main

  Deploy-Production:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    needs: [Test]
    steps:
      - uses: actions/checkout@v3
      - name: FRONTEND Install Vercel CLI
        run:  |
          cd frontend
          npm install --global vercel@canary
      - name: FRONTEND Pull Vercel Environment Information
        run:   |
          cd frontend
          vercel pull --yes --environment=production --token=${{ secrets.VERCEL_TOKEN }}
      - name: FRONTEND Build Project Artifacts
        run:   |
          cd frontend
          vercel build --prod --token=${{ secrets.VERCEL_TOKEN }}
      - name: FRONTEND Deploy Project Artifacts to Vercel
        run:   |
          cd frontend
          vercel deploy --prebuilt --prod --token=${{ secrets.VERCEL_TOKEN }}