name: GitHub Actions Vercel Deploy

env:
  VERCEL_ORG_ID: ${{ secrets.BACKEND_VERCEL_ORG_ID }}
  VERCEL_PROJECT_ID: ${{ secrets.BACKEND_VERCEL_PROJECT_ID }}
on:
  repository_dispatch:
    types: [deploy_backend]

jobs:
  Deploy-Backend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: BACKEND Install Vercel CLI
        run:  |
          cd backend
          npm install --global vercel@canary
      - name: BACKEND Pull Vercel Environment Information
        run:   |
          cd backend
          vercel pull --yes --environment=production --token=${{ secrets.VERCEL_TOKEN }}
      - name: BACKEND Build Project Artifacts
        run:   |
          cd backend
          vercel build --prod --token=${{ secrets.VERCEL_TOKEN }}
      - name: BACKEND Deploy Project Artifacts to Vercel
        run:   |
          cd backend
          vercel deploy --prebuilt --prod --token=${{ secrets.VERCEL_TOKEN }}
